dataset: weather

exp_id: 30
data_id: 30
test_time: '2020-01-10 00:10:00'
pred_starting_time: '2020-01-05 00:10:00'

# over-writing parameters
model_name: seq2seq

description: weather dataset generation. 5 days, 720 data points. true scale.

aheads: [1, 2, 3, 4]
smooth: False
fix_window: True
true_scale: True
total_steps: 20000   # maximum weeks
skip_beginning: 0
multi_seed: False
# rft
region_fine_tuning: False
rft_epochs: 200
rft_batch_size: 32
# week retraining: if False, use model state dict from previous week
week_retrain: True
week_retrain_epochs: 200
# skip weeks, train once and use the pretrained model state for a few weeks
week_retrain_period: 12

training_parameters:
  batch_size: 32
  epochs: 200
  gamma: 0.1
  lr: 0.00001
  patience: 50
model_parameters:
  hidden_dim: 128
  out_layer_dim: 64
  num_heads: 8
  num_layers: 4
  rnn_hidden_dim: 128
  rnn_layers: 8
